# Generated by Django 4.0.3 on 2022-07-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='passenger_berth_preference',
        ),
    ]
