# Generated by Django 4.0.3 on 2022-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_database_passenger_berth_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='passenger_names',
            new_name='passenger_name',
        ),
        migrations.AlterField(
            model_name='database',
            name='passenger_age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='database',
            name='passenger_senior_citizen',
            field=models.BooleanField(verbose_name='Is Senior Citizen'),
        ),
    ]
